"""initial schema

Revision ID: d6c85050648f
Revises: 
Create Date: 2026-07-09 22:12:42.405423

"""
from alembic import op
import sqlalchemy as sa


revision = 'd6c85050648f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_entries_tenant_id'), 'rate_limit_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_entries_timestamp'), 'rate_limit_entries', ['timestamp'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('succession_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_roster', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_succession_sessions_tenant_id'), 'succession_sessions', ['tenant_id'], unique=False)
    op.create_table('token_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_usages_tenant_created', 'token_usages', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usages_tenant_id'), 'token_usages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usages_tenant_id'), table_name='token_usages')
    op.drop_index('ix_token_usages_tenant_created', table_name='token_usages')
    op.drop_table('token_usages')
    op.drop_index(op.f('ix_succession_sessions_tenant_id'), table_name='succession_sessions')
    op.drop_table('succession_sessions')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_rate_limit_entries_timestamp'), table_name='rate_limit_entries')
    op.drop_index(op.f('ix_rate_limit_entries_tenant_id'), table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    # ### end Alembic commands ###
